# Generated by Django 4.2.30 on 2026-09-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
