# Generated by Django 4.2.25 on 2026-02-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_user_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp',
            new_name='login_otp',
        ),
        migrations.AddField(
            model_name='user',
            name='register_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
