# Generated by Django 4.2.30 on 2026-09-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cart_unique_user_product_cart'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_user_product_cart',
        ),
    ]
