# Generated by Django 4.2.25 on 2026-03-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='category/default.png', null=True, upload_to='category/'),
        ),
    ]
