# Generated by Django 4.2.30 on 2026-09-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='size',
            new_name='color_code',
        ),
    ]
