# Generated by Django 4.2.30 on 2026-10-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_rename_size_productvariant_color_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='title_name',
        ),
    ]
