# Generated by Django 4.2.30 on 2026-10-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_rename_title_product_title_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_name',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
